### ISSUE TITLE
Discussion over use of DataStructureDefinition and relationship on Dataset

### ISSUE THREAD

**Issue by javihern98** [bis-med-it/pysdmx#144]
Currently the Dataset class has the following attributes (Pandas Dataset adds data):

```python
class Dataset(Struct, frozen=False, kw_only=True):
    """Core Dataset class."""

    structure: Union[str, Schema]
    attributes: Dict[str, Any] = {}
    action: ActionType = ActionType.Information
    reporting_begin: Optional[date] = None
    reporting_end: Optional[date] = None
    data_extraction_date: Optional[date] = None
    valid_from: Optional[date] = None
    valid_to: Optional[date] = None
    publication_year: Optional[date] = None
    publication_period: Optional[date] = None
    set_id: Optional[str] = None
```

The structure attribute is related to Schema, precisely what is this class for? Does it have any use for Dataset if we implement the DataStructureDefinition class on #132 ?

**Comment by javihern98** [comment]
@sosna @stratosn Let me know your thoughts about this, it is important as well for the feature on automatic download of metadata for a Data Message

**Comment by sosna** [comment]
Minor comment: Maybe we can use the discussions board to capture questions, instead of capturing an issue?

To come back to your question, I believe that, for a Dataset, a reference to the schema is more appropriate, and this, for the following reason: A dataset maybe have been reported against either a data structure, or a dataflow or a provision agreement. The `DataStructureDefinition` class would support only the 1st use case, while the `Schema` would support all 3 (cf. Schema `context` property).

I hope this clarifies but else, happy to discuss.

**Comment by javihern98** [comment]
Yes, I should have used the Discussion board.

In any case, we should use then the Schema, as long as we can convert automatically these classes into the Schema class (maybe using a convenience method like to_schema in each class?

**Comment by sosna** [comment]
That sounds good, @javihern98

**Comment by javihern98** [comment]
Closing this issue, adding a comment in #57
